
name: github_trending_c
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
    
  c_github_trending_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/linux.json
          export number=0
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/obs-studio.json
          export number=1
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/jq.json
          export number=2
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/lede.json
          export number=3
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/bcc.json
          export number=4
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/timescaledb.json
          export number=5
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/ish.json
          export number=6
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/mimalloc.json
          export number=7
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/zephyr.json
          export number=8
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        

  c_github_trending_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/librdkafka.json
          export number=9
          export language=c
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          export jpg="cover.jpeg"
          python run.py        
