
name: github_trending_go
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
    
  go_github_trending_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/syncthing.json
          export number=0
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_syncthing"
          export jpg="figures/go_0.png"
          python run.py        

  go_github_trending_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/go-ethereum.json
          export number=1
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_go-ethereum"
          export jpg="figures/go_1.png"
          python run.py        

  go_github_trending_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/clash.json
          export number=2
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_clash"
          export jpg="figures/go_2.png"
          python run.py        

  go_github_trending_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/beego.json
          export number=3
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_beego"
          export jpg="figures/go_3.png"
          python run.py        

  go_github_trending_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/fiber.json
          export number=4
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_fiber"
          export jpg="figures/go_4.png"
          python run.py        

  go_github_trending_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/lux.json
          export number=5
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_lux"
          export jpg="figures/go_5.png"
          python run.py        

  go_github_trending_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/Cloudreve.json
          export number=6
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_Cloudreve"
          export jpg="figures/go_6.png"
          python run.py        

  go_github_trending_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/alist.json
          export number=7
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_alist"
          export jpg="figures/go_7.png"
          python run.py        

  go_github_trending_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/rqlite.json
          export number=8
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_rqlite"
          export jpg="figures/go_8.png"
          python run.py        

  go_github_trending_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/age.json
          export number=9
          export language=go
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_go_age"
          export jpg="figures/go_9.png"
          python run.py        
