
name: github_trending_python
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
    
  python_github_trending_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/system-design-primer.json
          export number=0
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_system-design-primer"
          export jpg="figures/python_0.png"
          python run.py        

  python_github_trending_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/Python.json
          export number=1
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_Python"
          export jpg="figures/python_1.png"
          python run.py        

  python_github_trending_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/awesome-python.json
          export number=2
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_awesome-python"
          export jpg="figures/python_2.png"
          python run.py        

  python_github_trending_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/Python-100-Days.json
          export number=3
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_Python-100-Days"
          export jpg="figures/python_3.png"
          python run.py        

  python_github_trending_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/core.json
          export number=4
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_core"
          export jpg="figures/python_4.png"
          python run.py        

  python_github_trending_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/ansible.json
          export number=5
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_ansible"
          export jpg="figures/python_5.png"
          python run.py        

  python_github_trending_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/you-get.json
          export number=6
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_you-get"
          export jpg="figures/python_6.png"
          python run.py        

  python_github_trending_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/DeepFaceLab.json
          export number=7
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_DeepFaceLab"
          export jpg="figures/python_7.png"
          python run.py        

  python_github_trending_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/diagrams.json
          export number=8
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_diagrams"
          export jpg="figures/python_8.png"
          python run.py        

  python_github_trending_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/GFPGAN.json
          export number=9
          export language=python
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_python_GFPGAN"
          export jpg="figures/python_9.png"
          python run.py        
