
name: github_trending_java
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
    
  java_github_trending_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/jeecg-boot.json
          export number=0
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_jeecg-boot"
          export jpg="figures/java_0.png"
          python run.py        

  java_github_trending_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/Signal-Android.json
          export number=1
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_Signal-Android"
          export jpg="figures/java_1.png"
          python run.py        

  java_github_trending_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/NewPipe.json
          export number=2
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_NewPipe"
          export jpg="figures/java_2.png"
          python run.py        

  java_github_trending_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/FizzBuzzEnterpriseEdition.json
          export number=3
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_FizzBuzzEnterpriseEdition"
          export jpg="figures/java_3.png"
          python run.py        

  java_github_trending_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/Mindustry.json
          export number=4
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_Mindustry"
          export jpg="figures/java_4.png"
          python run.py        

  java_github_trending_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/jd-gui.json
          export number=5
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_jd-gui"
          export jpg="figures/java_5.png"
          python run.py        

  java_github_trending_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/DSA-Bootcamp-Java.json
          export number=6
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_DSA-Bootcamp-Java"
          export jpg="figures/java_6.png"
          python run.py        

  java_github_trending_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/lawnchair.json
          export number=7
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_lawnchair"
          export jpg="figures/java_7.png"
          python run.py        

  java_github_trending_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/alluxio.json
          export number=8
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_alluxio"
          export jpg="figures/java_8.png"
          python run.py        

  java_github_trending_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          export json_file=configs/baritone.json
          export number=9
          export language=java
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
          # wecover "GithubTrending_java_baritone"
          export jpg="figures/java_9.png"
          python run.py        
