name: github_trending
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  python_github_trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: get Environment
        run: |
          sudo apt update
          sudo apt install ffmpeg
          export refresh_token="${{ secrets.refresh_token }}"
          export access_token="${{ secrets.access_token }}"
          pip install git+https://github.com/FortuneDayssss/BilibiliUploader.git
          pip install -r requirements.txt
      # - name: download musics for background
      #   run: |
      #     ./download_music.bash
      - name: record and upload
        run: |
          python run.py
