name: updates

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update_my_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Get install
        run: |
          pip install -r requirements.txt
          pip install bilibili-api-python
      - name: Update config
        run: |
          python generate_config.py
      - name: push to the remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add . ; git commit -m "auto update configuration"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
